# Generated by Django 3.1.6 on 2021-02-18 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('patronymick', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=256)),
                ('sex', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('patronymick', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=256)),
                ('sex', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('password', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=20)),
                ('medical_insurance', models.BooleanField()),
                ('my_doctor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='medcard.doctor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
