# Generated by Django 3.1.6 on 2021-02-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='my_doctor',
            field=models.CharField(max_length=20),
        ),
    ]
