# Generated by Django 3.1.6 on 2021-05-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='result',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='description',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='description',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='visit',
            name='result',
            field=models.JSONField(default=dict),
        ),
    ]
