# Generated by Django 3.1.6 on 2021-03-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
