# Generated by Django 3.1.6 on 2021-03-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medcard', '0002_auto_20210307_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6),
        ),
    ]
