# Generated by Django 3.1.6 on 2021-05-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medcard', '0002_auto_20210529_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='end_data',
            field=models.DateField(blank=True),
        ),
    ]
