# Generated by Django 3.1.6 on 2021-02-18 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medcard', '0002_auto_20210218_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='my_doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='medcard.doctor'),
        ),
    ]
