# Generated by Django 3.1.6 on 2021-02-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medcard', '0003_auto_20210218_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='clinical',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
