# Generated by Django 3.1.6 on 2021-02-18 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medcard', '0004_doctor_clinical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='clinical',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='medcard.clinical'),
        ),
    ]
