# Generated by Django 3.1.6 on 2021-05-30 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medcard', '0004_auto_20210530_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='end_data',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='disease',
            old_name='start_data',
            new_name='start_date',
        ),
    ]
