# Generated by Django 3.1.6 on 2021-02-20 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medcard', '0006_medicalprocedures'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Main',
            new_name='MedicalHistory',
        ),
    ]
