# Generated by Django 3.1.6 on 2021-02-20 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medcard', '0009_medicalhistory_medical_procedures'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprocedures',
            name='in_clinik',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='medcard.clinical'),
        ),
    ]
