# Generated by Django 3.1.6 on 2021-02-20 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medcard', '0012_auto_20210220_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='my_med_history',
        ),
        migrations.AddField(
            model_name='examination',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='medcard.doctor'),
        ),
        migrations.AddField(
            model_name='examination',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='vaccine',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
