# Generated by Django 3.1.6 on 2021-02-20 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medcard', '0013_auto_20210220_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medcard.doctor'),
        ),
    ]
