# Generated by Django 3.1.6 on 2021-02-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medcard', '0014_auto_20210220_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='patient_status',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='visit_purpose',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
