# Generated by Django 3.1.6 on 2021-02-20 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medcard', '0016_auto_20210220_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='clinical',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medcard.clinical'),
        ),
        migrations.AddField(
            model_name='examination',
            name='clinical',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medcard.clinical'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='clinical',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medcard.clinical'),
        ),
        migrations.AddField(
            model_name='operation',
            name='clinical',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medcard.clinical'),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='clinical',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medcard.clinical'),
        ),
    ]
