# Generated by Django 3.1.6 on 2021-02-20 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medcard', '0017_auto_20210220_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalPurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('direction', models.CharField(max_length=256, null=True)),
                ('clinical', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medcard.clinical')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medcard.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='analysis',
            name='name_analysis',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='result_analysis',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medcard.doctor'),
        ),
        migrations.AddField(
            model_name='operation',
            name='info',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='info',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='Inspection',
        ),
    ]
